{% set name = "westpa" %}
{% set version = "2020.07" %}
{% set sha256 = "09d1521345eaf9a2894261d7f42407ced694d9b07dc8a6e163ec0d3b4104439a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/westpa/westpa/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [win or py2k or py>39]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - setuptools
    - python
    - cython <3.0.3
    - numpy 1.21.*
  run:
    - python
    - numpy 1.21.*
    - scipy
    - h5py 2.10.*
    - pyyaml 5.3.*
    - pyzmq 19.0.*
    - matplotlib-base
    - blessings 1.7.*
    - ipykernel

test:
  commands:
    - "source ${PREFIX}/${PKG_NAME}-${PKG_VERSION}/westpa.sh"
    - "source ${WEST_ROOT}/bin/w_env"
    - "$WEST_PYTHON -c 'import west'"
    - "$WEST_PYTHON -c 'import west.propagators'"
    - "$WEST_PYTHON -c 'import westpa'"
    - "$WEST_PYTHON -c 'import westpa.binning'"
    - "$WEST_PYTHON -c 'import westpa.kinetics'"
    - "$WEST_PYTHON -c 'import westpa.reweight'"
    - "$WEST_PYTHON -c 'import work_managers'"
    - "$WEST_PYTHON -c 'import westtools'"
    - "$WEST_PYTHON -c 'import fasthist'"
    - "$WEST_PYTHON -c 'import mclib'"
    # Currently blocked by https://github.com/westpa/westpa/issues/70
    #- "$WEST_PYTHON -c 'import trajtree'"

about:
  home: https://westpa.github.io/westpa
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Interoperable, highly-scalable software for weighted ensemble simulation.'

  description: |
    WESTPA is a package for constructing and running stochastic simulations
    using the "weighted ensemble" approach of Huber and Kim (1996).
  doc_url: https://westpa.github.io/westpa/sphinx_index.html#tutorials
  dev_url: https://github.com/westpa

extra:
  recipe-maintainers:
    - mczwier
    - ajoshpratt
    - synapticarbors
    - burntyellow
    - ltchong
    - jeremyleung521
