{% set name = "westpa" %}
{% set version = "2.0b6" %}
{% set sha256 = "d6665a2cc90a17b44152f37168e650624f0dbf80acf8029ed73c1b058fa8fa73" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/jeremyleung521/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  #  url: https://files.pythonhosted.org/packages/fe/e9/e9ef53a71a73dfe76a8875a8eb2ce1c16942a7878502270922c5fdc8016f/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win or py2k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - setuptools>=40.8.0
    - python
    - wheel
    - cython>=0.29.16
    - numpy>=1.16
    - scipy>=0.19.1
    - versioneer-518
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy>=0.19.1
    - h5py>=2.10
    - mdtraj>=1.9.5
    - pyyaml 5.3.*
    - pyzmq 19.0.*
    - matplotlib-base
    - blessings 1.7.*
    - ipykernel
    - tqdm
    - pandas
    - pytables

test:
  imports:
    - westpa
    - westpa.core.propagators
    - westpa.core.binning
    - westpa.core.kinetics
    - westpa.core.reweight
    - westpa.work_managers
    - westpa.tools
    - westpa.fasthist
    - westpa.mclib
    # Currently blocked by https://github.com/westpa/westpa/issues/70
    #- westpa.trajtree
  source_files:
{% if tests == "run"%}
    - tests/*.py
    - tests/test_tools
    - tests/refs
    - tests/fixtures
{% endif %}
  requires:
{% if tests == "run"%}
    - pytest
    - nose
{% endif %}
  commands:
{% if tests == "run"%}
    - pytest -v tests/
{% endif %}

about:
  home: https://westpa.github.io/westpa
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Interoperable, highly-scalable software for weighted ensemble simulation.'

  description: |
    WESTPA is a package for constructing and running stochastic simulations
    using the "weighted ensemble" approach of Huber and Kim (1996).
  doc_url: https://westpa.readthedocs.io/westpa/en/latest
  dev_url: https://github.com/westpa

extra:
  recipe-maintainers:
    - mczwier
    - synapticarbors
    - burntyellow
    - ltchong
    - jeremyleung521
