schema_version: 1

context:
  name: westpa
  version: 2022.12
  sha256: c5b77bf9ee0c046d50665aa739d29b4a16176b320e8742ed39dc90870e3f8ca0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/westpa/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ${{ sha256 }}
  file_name: ${{ name }}-${{ version }}.tar.gz

build:
  number: 1
  skip: win
  script: ${{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython >=0.29.16
        - numpy >=2.0.0,<3
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - setuptools >=40.8.0
    - python
    - wheel
    - cython >=0.29.16
    - numpy >=2.0.0,<3
    - scipy >=0.19.1
    - versioneer-518
    - pip
  run:
    - python
    - numpy >=1.25.0,<3
    - scipy >=0.19.1
    - h5py >=2.10
    - mdtraj >=1.9.5
    - pyyaml >=5.3
    - pyzmq >=19.0
    - matplotlib-base
    - blessings 1.7.*
    - ipykernel
    - tqdm
    - pandas
    - pytables

tests:
  - python:
      imports:
        - westpa
        - westpa.core.propagators
        - westpa.core.binning
        - westpa.core.kinetics
        - westpa.core.reweight
        - westpa.work_managers
        - westpa.tools
        - westpa.fasthist
        - westpa.mclib

about:
  license: MIT
  license_file: LICENSE
  summary: Interoperable, highly-scalable software for weighted ensemble simulation.
  description: |
    WESTPA is a package for constructing and running stochastic simulations
    using the "weighted ensemble" approach of Huber and Kim (1996).
  homepage: https://westpa.github.io/westpa
  repository: https://github.com/westpa
  documentation: https://westpa.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - mczwier
    - synapticarbors
    - burntyellow
    - ltchong
    - jeremyleung521
