# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Q43x/UWJjODnZY68BAw3qwFSQ/flK8YljMBCYSSQSq5ip7+OqP1Xo+j2gY4/O2iCfzBF47ToGF5Zy+V6J3xJGbaFGl5NhwJ+OBhCVevC9NuCD525JBdOa/mKoeQKVs5jkQY+CUQmwsNJJatKkhKsG5ZsAYDciduc0vKsNNvQz9u74tYga2uWqD1s9OCmLa6QK1pAgnhCBJXh+dfp5laKoiRLNb3AeKRkyFx0bn3ZQAuc0AuaV3vmeu/i9RgSvQGSzEvnZ79CRXJqhdaGjZkxuDoDUpIjEkTTZlrCbNX8gi5eFQn5baf/KdY8cuAvVWG50hnlwfCfnDiD0P14dEbvbTdK5o697G4P17GLuArQrUxq/P3W/57sPH823WY2/8ADupDiFc9pvO3sPBXj592gFZzS7eHRKqVP23NyvUMGpZtdHAfxyUTmRYOPMbAsp26KOGTdhgYRM/qrmtYfMSWAozr3UROtsn9bqNF84VgLO/bMNVPSpLHW/zDCsMq0RIsEl31wLSmfw/y/pUlA5HEizXwjOi6rj7KMSiBuBgBjv3Nk+iQIVR09/2buScSYslDzehYoTbmp9tKfhOZ1rAByNG9JGhJXWea1825LrhW1JZOKqMZbYKrG5AHVUwFJcijhuQ2y7WM1v4KgyybAzR5iPFTYui8sKw6X5YnePK1w36w="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
