travis:
  secure:
    BINSTAR_TOKEN: Q43x/UWJjODnZY68BAw3qwFSQ/flK8YljMBCYSSQSq5ip7+OqP1Xo+j2gY4/O2iCfzBF47ToGF5Zy+V6J3xJGbaFGl5NhwJ+OBhCVevC9NuCD525JBdOa/mKoeQKVs5jkQY+CUQmwsNJJatKkhKsG5ZsAYDciduc0vKsNNvQz9u74tYga2uWqD1s9OCmLa6QK1pAgnhCBJXh+dfp5laKoiRLNb3AeKRkyFx0bn3ZQAuc0AuaV3vmeu/i9RgSvQGSzEvnZ79CRXJqhdaGjZkxuDoDUpIjEkTTZlrCbNX8gi5eFQn5baf/KdY8cuAvVWG50hnlwfCfnDiD0P14dEbvbTdK5o697G4P17GLuArQrUxq/P3W/57sPH823WY2/8ADupDiFc9pvO3sPBXj592gFZzS7eHRKqVP23NyvUMGpZtdHAfxyUTmRYOPMbAsp26KOGTdhgYRM/qrmtYfMSWAozr3UROtsn9bqNF84VgLO/bMNVPSpLHW/zDCsMq0RIsEl31wLSmfw/y/pUlA5HEizXwjOi6rj7KMSiBuBgBjv3Nk+iQIVR09/2buScSYslDzehYoTbmp9tKfhOZ1rAByNG9JGhJXWea1825LrhW1JZOKqMZbYKrG5AHVUwFJcijhuQ2y7WM1v4KgyybAzR5iPFTYui8sKw6X5YnePK1w36w=
provider:
  linux_ppc64le: default
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
